### ISSUE TITLE
Minimize Region Selector

### ISSUE THREAD

**Issue by Mush-r00m** [MathewSachin/Captura#251]
Would it be possible to add icons on the region selector to minimize/minimize to system tray?
Example:
https://imgur.com/a/YARDsUE

Also, when hovering over icons on the region selector the popups appear inside the region, which can be a problem during recordings, can they be moved to pop up outside the region?

 Side note, Personally i never use the canvas tools so having them on the region selector is abit cluttered to me, having an option to remove them as well would be great, but not very important.

**Comment by MathewSachin** [comment]
The region selector is not intended to be minimized, you can use the house during recording option if you want. 
BTW I'm planning to work on a drag and select region feature like what most softwares have.

As of now i suppose i would remove the tooltips.

Will not be able to add the option to remove the canvas tools soon because it affects the region size and require testing.
