### ISSUE TITLE
Record a keystroke if i release the key

### ISSUE THREAD

**Issue by uwe367** [MathewSachin/Captura#270]
I create video tutorials and i noticed that Captura records keystrokes if i release a key.
For example i press in a graphic programm the strg-Button. This is displayed correctly. But if i release this Button, it will be displayed in the video too.
Is there any place you can set this or is it perhaps a bug?

I´m using WIN10, newest Updates and i noticed this behavior in the current version 7.0.1 and also in version 8.0.0 here from github.

**Comment by MathewSachin** [comment]
I'm not sure if I understood correctly (Please correct if I understood wrong), but if you're trying to turn off keystroke recording, it's next to mouse cursor and mouse click overlays.

![inked2018-09-26-22-59-48_li](https://user-images.githubusercontent.com/10654537/46097696-29079d00-c1e0-11e8-929c-b489d3802834.jpg)

Otherwise modifier keys (Control, Alt, Shift) are shown when released. Otherwise it would lead to repeated display like in case with other keys (e.g. alphabets).

**Comment by uwe367** [comment]
Ah ok, i understand.
No, i don´t want turn off keystroke recording, i need it for my work.
I didn´t know that modifier keys would lead to display with ohter keys if they are not shown when released. So the function i saw as mistake, is fine and the issue can be closed.
Thanks for your explaining :) 

P.s.
It´s a very good Screen recoder that has everything i need.
