### ISSUE TITLE
Can I live Stream?

### ISSUE THREAD

**Issue by nsmith1024** [MathewSachin/Captura#365]
Hello,

I want to write a client viewer program that can connect to Captura using a socket connection, where Capture would act like a server accepting multiple socket connections from various people using my client viewer program.

Captura would then stream its desktop + audio + keyboard + mouse live to all the viewers who connect.

Would it be possible for me to modify Captura to be able to do that?

Does it stream using a video format or some other format or method?

Can it use GPU compression to increase the speed?

Thanks

**Comment by MathewSachin** [comment]
Captura uses FFmpeg for live streaming in FLV format. At the moment you can stream to services like Twitch.

As far as I can understand from the [FFmpeg docs](https://trac.ffmpeg.org/wiki/StreamingGuide), you would need a seperate Server from ffmpeg (like ffserver) which would forward data received from ffmpeg to multiple clients. In this case Captura would not need to be modified, just the Custom streaming url would need to be set to your server's receiving url.

GPU compression can be done by FFmpeg, but at the moment I've not succeeded in implementing it satisfactory. Also, I've heard from other developers that they prefer CPU compression over GPU when streaming because GPU compression needs more bitrate for the same quality than CPU compression.

**Comment by nsmith1024** [comment]
Thanks for your answer.

So basically i would set it up like this on my home computer

desktop --> Captura --> ffmpeg --> ffserver

multiple people remotely can connect to the IP address of the ffserver, then be able to see and hear my desktop using any video player?

So if i want to stream my game play just to my friends, i can set that up and give my friends the IP address, correct?

**Comment by nsmith1024** [comment]
hmmm seems there is no ffserver for windows :( only linux

**Comment by MathewSachin** [comment]
The ffmpeg site mentions some alternatives

https://trac.ffmpeg.org/wiki/StreamingGuide

> Servers which can receive from FFmpeg (to restream to multiple clients) include ffserver (linux only, though with cygwin it might work on windows), or ​Wowza Media Server, or ​Flash Media Server, Red5, or ​various others. Even ​VLC can pick up the stream from ffmpeg, then redistribute it, acting as a server. Since FFmpeg is at times more efficient than VLC at doing the raw encoding, this can be a useful option compared to doing both transcoding and streaming in VLC. ​Nginx also has an rtmp redistribution plugin, as does ​apache etc. and there is probably more out there for apache, etc.. You can also live stream to online redistribution servers like own3d.tv or justin.tv (for instance streaming your desktop). Also any ​rtmp server will most likely work to receive streams from FFmpeg (these typically require you to setup a running instance on a server).

**Comment by MathewSachin** [comment]
Closing due to no reply. You may reopen if you wish to discuss further.
