### ISSUE TITLE
Portable settings

### ISSUE THREAD

**Issue by StormFenrir** [MathewSachin/Captura#376]
Hi!

The portable version leave settings in "\AppData\Roaming\Captura". Setting not copied into the program's folder and when I use it on another computer, lose the settings and can't find the FFMPEG. I have to add again the path always.

Can't add path like ".\Captura\Settings" or ".\Captura\FFMPEG\". The software accept only full path... I think it is not "portable". :)

Thanks!

**Comment by MathewSachin** [comment]
I've done some changes regarding portability of Settings and FFmpeg folders.

Here's a dev build to test: https://ci.appveyor.com/api/buildjobs/m29qt216g8vf8g28/artifacts/Captura-Portable.zip

If the app directory contains a directory named `Settings`, then it is used for storing settings instead of `AppData` path.
If the app directory contains a directory named `Codecs`, then it is used as FFmpeg folder by default if another folder is not specified in settings.
Also, a variable `%CAPTURA_PATH%` is now supported in specifying paths in the Settings file which resolve to the app directory.

**Comment by StormFenrir** [comment]
Works perfectly! Thank you! Have a nice day! :)
