### ISSUE TITLE
Version 9.0.0: Video region records the whole screen

### ISSUE THREAD

**Issue by Godly75** [MathewSachin/Captura#400]
Seems that in Version 9.0.0the Video region records the whole screen? Or am I missing a setting?
Also, the notifications don't dissapear after a while? (keeps on saying,... saving video...)
And captura interface doesn't appear again after hiding during recoring?

**Comment by MathewSachin** [comment]
Do these issues happen in the latest dev build?
Please test: https://ci.appveyor.com/api/buildjobs/4kifwqjh9qitotjm/artifacts/Captura-Portable.zip
I think some of them have already been fixed.

`Saving video...` might be shown for formats which do post-processing, i.e. convert the video to selected format after recording is done. This might be time consuming depending on the format and length of the video. Please let me know if this happens for `Mp4 H.264` or `AVI` formats.

I'd removed the interface showing after recording is over because it did not always work as expected.
e.g. The interface pops up when you don't really want it to.
Instead I added an a new Hotkey option for showing Main window.

**Comment by Godly75** [comment]
thx i'll try the latest dev. It's hard to find the latest here always. Very confusing.

**Comment by Godly75** [comment]
Are these the latest?
https://github.com/MathewSachin/Captura/releases

**Comment by MathewSachin** [comment]
No, those are Release builds.

For, getting the latest dev builds, follow the instructions on this page: https://mathewsachin.github.io/Captura/getting-started

**Comment by Godly75** [comment]
ok now where do I click? 
https://ci.appveyor.com/project/MathewSachin/Captura

**Comment by Godly75** [comment]
Can you send me the latest beta? I just can't find it?

**Comment by MathewSachin** [comment]
https://github.com/MathewSachin/Captura/releases/download/v9.0.0-beta3/Captura-Portable.zip

**Comment by MathewSachin** [comment]
@Godly75 Is your problem solved in the dev build I provided in the above comment?

**Comment by MathewSachin** [comment]
I'm closing this issue for now, if you still face the issue please reopen.

**Comment by Godly75** [comment]
Hi Mathew,
The dev builds are moved. Where can I find them now?

Met vriendelijke groeten | Bien à vous | Best regards,
Sven Godijn
Tel:// +32 (0)475/879 275
Skype: encountersmedia


Op di 30 apr. 2019 om 15:06 schreef Mathew Sachin <notifications@github.com

**Comment by MathewSachin** [comment]
See the instructions [here](https://github.com/MathewSachin/Captura/blob/master/docs/CI.md).
Dev builds have not moved but the documentation has moved to this repo.
