### ISSUE TITLE
Portable: How to fix multiple instances execution?

### ISSUE THREAD

**Issue by bogacg** [MathewSachin/Captura#504]
If I execute multiple instances of Captura (portable), it is allowed to my surprise, with expected problems like error for hotkeys and recordings get saved after each instances are closed...

Is there a setting I'm missing that prevent re-execution of Captura if one is already working on screen/taskbar?

Thank you

**Comment by MathewSachin** [comment]
This was something other users had asked before, but I put it off due to not having much time to study and implement it.
Now, since I had some time, I've tried an implementation (#505) and seems to work fine so far.

Here's a build to test: https://ci.appveyor.com/api/buildjobs/6sbs6dgp9mfc56bi/artifacts/temp%2FCaptura-Portable.zip
Do note that this is a development build and is much different from the released versions.
